[package]
name = "avera"
version = "2026.0.1"
edition = "2021"
rust-version = "1.81"
description = "một ngôn ngữ được tôi lọ ra trong lúc chán"
license = "MIT OR Apache-2.0"
build = "build.rs"

[[bin]]
name = "avera"
path = "src/main.rs"

[lib]
name = "avera_compiler"
path = "src/lib.rs"

[dependencies]
cranelift-codegen = "0.115.1"
cranelift-frontend = "0.115.1"
cranelift-module = "0.115.1"
cranelift-object = "0.115.1"
cranelift-native = "0.115.1"
target-lexicon = "0.12.16"
bumpalo = "3"
thiserror = "2"
once_cell = "1"

[profile.release]
opt-level = 2
panic = "abort"
lto = "thin"
codegen-units = 1

[profile.dev]
opt-level = 0
panic = "abort"
